# -*- coding: utf-8 -*-
"""Dimensionality Reduction ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gAisUu0fK3DinAiYIqqpA1MPwVCjtG3
"""

# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns  # type: ignore[import-untyped]
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures

# ---------------------------------------------------------------------------
# Manual loading of Boston housing dataset (load_boston is deprecated)
# ---------------------------------------------------------------------------
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)

# ---------------------------------------------------------------------------
# Format Data
# ---------------------------------------------------------------------------
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

# Mimic the structure of the original load_boston return value for compatibility
# Note: 'feature_names' are placeholders, and 'DESCR' is a simplified one.
boston = {
    'data': data,
    'target': target,
    'feature_names': [
        'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM',
        'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'
    ],
    'DESCR': (
        "Boston Housing dataset (manually loaded). "
        "Original scikit-learn 'load_boston' is deprecated due to ethical concerns."
    )
}

print(boston['DESCR'])

# ---------------------------------------------------------------------------
# Train / Test Split
# ---------------------------------------------------------------------------
data_train, data_test, target_train, target_test = train_test_split(
    boston['data'], boston['target'], test_size=0.2, random_state=42
)

# ---------------------------------------------------------------------------
# Apply PCA
# ---------------------------------------------------------------------------
pca = PCA(n_components=2)
data_train_pca = pca.fit_transform(data_train)

# Plot the PCA Results
plt.figure(figsize=(10, 6))
plt.scatter(data_train_pca[:, 0], data_train_pca[:, 1], c=target_train, cmap='viridis')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Boston Housing Data')
plt.colorbar(label='Target')
plt.show()

# ---------------------------------------------------------------------------
# Apply t-SNE
# ---------------------------------------------------------------------------
tsne = TSNE(n_components=2, random_state=42)
data_train_tsne = tsne.fit_transform(data_train)

# Plot t-SNE Results
plt.figure(figsize=(10, 6))
plt.scatter(data_train_tsne[:, 0], data_train_tsne[:, 1], c=target_train, cmap='viridis')
plt.xlabel('t-SNE Component 1')
plt.ylabel('t-SNE Component 2')
plt.title('t-SNE of Boston Housing Data')
plt.colorbar(label='Target')
plt.show()

# ---------------------------------------------------------------------------
# Model Training and Evaluation (Without PCA)
# ---------------------------------------------------------------------------
ridge_model_no_pca = Ridge(alpha=1.0)
ridge_model_no_pca.fit(data_train, target_train)

target_pred_no_pca = ridge_model_no_pca.predict(data_test)

mse_no_pca = mean_squared_error(target_test, target_pred_no_pca)
r2_no_pca = r2_score(target_test, target_pred_no_pca)

print("--- Performance Without PCA ---")
print(f"Mean Squared Error: {mse_no_pca:.2f}")
print(f"R-squared: {r2_no_pca:.2f}")

# ---------------------------------------------------------------------------
# Model Training and Evaluation (With PCA)
# ---------------------------------------------------------------------------
# Transform the test data using the already-fitted PCA object
data_test_pca = pca.transform(data_test)

ridge_model_pca = Ridge(alpha=1.0)  # Same alpha for fair comparison
ridge_model_pca.fit(data_train_pca, target_train)

target_pred_pca = ridge_model_pca.predict(data_test_pca)

mse_pca = mean_squared_error(target_test, target_pred_pca)
r2_pca = r2_score(target_test, target_pred_pca)

print("--- Performance With PCA (2 components) ---")
print(f"Mean Squared Error: {mse_pca:.2f}")
print(f"R-squared: {r2_pca:.2f}")

# ---------------------------------------------------------------------------
# Comparison of Performance
# ---------------------------------------------------------------------------
print("\n--- Summary of Initial Performance ---")
print(f"Without PCA: R-squared = {r2_no_pca:.2f}, MSE = {mse_no_pca:.2f}")
print(f"With PCA (2 components): R-squared = {r2_pca:.2f}, MSE = {mse_pca:.2f}")

print("\nInterpretation:")
print(
    "  - R-squared: Proportion of variance explained by the model. "
    "Higher is better."
)
print(
    "  - MSE: Average squared difference between predicted and actual values. "
    "Lower is better."
)

if r2_pca > r2_no_pca:
    print(
        f"\nPCA improved R-squared from {r2_no_pca:.2f} to {r2_pca:.2f} "
        "and decreased the MSE."
    )
elif r2_pca < r2_no_pca:
    print(
        f"\nPCA reduced R-squared from {r2_no_pca:.2f} to {r2_pca:.2f} "
        "and increased the MSE. Reducing to 2 components lost important information."
    )
else:
    print("\nPCA had no significant impact on R-squared or MSE.")

# ---------------------------------------------------------------------------
# Feature Engineering (Polynomial Features)
# ---------------------------------------------------------------------------
# Create polynomial features up to degree 2
# Generates: linear (x), squared (x^2), and cross-product terms (x*y)
poly = PolynomialFeatures(degree=2, include_bias=False)

data_train_poly = poly.fit_transform(data_train)
data_test_poly = poly.transform(data_test)

poly_feature_names = poly.get_feature_names_out(boston['feature_names'])

print(f"Original number of features: {data_train.shape[1]}")
print(f"Features after polynomial transformation (degree 2): {data_train_poly.shape[1]}")
print("First 5 polynomial feature names:", poly_feature_names[:5].tolist())

# ---------------------------------------------------------------------------
# Retrain and Evaluate Model with Polynomial Features
# ---------------------------------------------------------------------------
ridge_model_poly = Ridge(alpha=1.0)
ridge_model_poly.fit(data_train_poly, target_train)

target_pred_poly = ridge_model_poly.predict(data_test_poly)

mse_poly = mean_squared_error(target_test, target_pred_poly)
r2_poly = r2_score(target_test, target_pred_poly)

print("--- Performance With Polynomial Features (Degree 2) ---")
print(f"Mean Squared Error: {mse_poly:.2f}")
print(f"R-squared: {r2_poly:.2f}")

# ---------------------------------------------------------------------------
# Final Comparison of All Models
# ---------------------------------------------------------------------------
print("\n--- Final Model Performance Comparison ---")
print(f"1. Ridge without PCA (Baseline):\tR-squared = {r2_no_pca:.2f}, MSE = {mse_no_pca:.2f}")
print(f"2. Ridge with PCA (2 components):\tR-squared = {r2_pca:.2f}, MSE = {mse_pca:.2f}")
print(f"3. Ridge with Polynomial Features:\tR-squared = {r2_poly:.2f}, MSE = {mse_poly:.2f}")

print("\n--- Interpretation ---")
if r2_poly > max(r2_no_pca, r2_pca):
    print(
        "Polynomial Features (Degree 2) achieved the best R-squared score. "
        "Feature engineering significantly improved the model!"
    )
elif r2_no_pca > max(r2_poly, r2_pca):
    print(
        "Ridge without PCA performed best. The original 13 features were strong "
        "and polynomial expansion did not add value here."
    )
elif r2_pca > max(r2_no_pca, r2_poly):
    print(
        "Ridge with PCA (2 components) performed best, which is unexpected. "
        "These 2 components may have captured the most predictive variance."
    )
else:
    print("Models performed similarly; polynomial features showed marginal improvement.")

# ---------------------------------------------------------------------------
# Visual Comparison of Model Performance
# ---------------------------------------------------------------------------
model_names = [
    'Ridge without PCA',
    'Ridge with PCA (2 components)',
    'Ridge with Polynomial Features'
]
r2_scores = [r2_no_pca, r2_pca, r2_poly]
mse_scores = [mse_no_pca, mse_pca, mse_poly]

performance_df = pd.DataFrame({
    'Model': model_names,
    'R-squared': r2_scores,
    'MSE': mse_scores
})

print("Model Performance Summary:")
print(performance_df)

# Plot R-squared comparison
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='R-squared', data=performance_df, palette='viridis')
plt.title('R-squared Comparison of Different Models')
plt.ylabel('R-squared Score')
plt.ylim(0, 1)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Plot MSE comparison
plt.figure(figsize=(12, 6))
sns.barplot(x='Model', y='MSE', data=performance_df, palette='magma')
plt.title('Mean Squared Error (MSE) Comparison of Different Models')
plt.ylabel('Mean Squared Error')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()